### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by drnextgis** [ghettovoice/ol3-popup-umd#3]
Trying to install using npm and get an error:

```
UNMET PEER DEPENDENCY openlayers@>= 3.14
```

**Comment by ghettovoice** [comment]
Hi!
You need to install `openlayers` package manually.
Try command: `npm i --save openlayers ol3-popup-umd`.
Or add `"openlayers": "^3.20"` under `dependencies` section  in your package.json and execute command: `npm i`. Than you can install ol3-popup-umd package.

**Comment by drnextgis** [comment]
Thanks it helps. But is it expected behavior that user have to modify package.json or install dependencies manually?

**Comment by ghettovoice** [comment]
Yes, it is expected behavior for [peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/).
ol3-popup-umd is an plugin for [OpenLayers](http://openlayers.org/), for use it you should install openlayers package anyway.
